<?php

namespace ContainerX3V3uzI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBTCEURRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\BTCEURRepository' shared autowired service.
     *
     * @return \App\Repository\BTCEURRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/src/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepositoryProxy.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/Traits/TruncateTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/Traits/DateTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/BTCEURRepository.php';

        return $container->privates['App\\Repository\\BTCEURRepository'] = new \App\Repository\BTCEURRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
